parser: babel-eslint
extends:
  - airbnb-base
  - prettier
  - prettier/flowtype
plugins:
  - flowtype
  - jest
rules:
  valid-typeof:
    - error
    -
      requireStringLiterals: false
  class-methods-use-this:
    - off
