language: node_js
cache:
  directories:
    - node_modules
    - .tmp
notifications:
  email: false
before_install:
  - git fetch --tags

stages:
  - name: test
    # require the event type to not be a semantic release tag.
    if: NOT tag =~ ^v\d+\.\d+\.\d+$

jobs:
  include:
    -
      stage: test
      node_js: 'lts/carbon'
      before_install:
        - git fetch origin --tags
        - yarn global add greenkeeper-lockfile@1
        - gem install redis
      before_script:
        - greenkeeper-lockfile-update
        - yarn create-cluster
      after_script:
        - greenkeeper-lockfile-upload
        - yarn destroy-cluster
      script:
        - yarn lint
        - yarn test-ci
        - yarn add --no-lockfile coveralls
        # Report coverage to coveralls.io
        - cat ./__coverage__/lcov.info | ./node_modules/coveralls/bin/coveralls.js
        - rm -fr ./__coverage__

    -
      stage: deploy
      if: branch = master
      # Semantic release will fail if it's not using node 8.
      node_js: 'lts/carbon'
      script: yarn semantic-release
