name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15
          cache: yarn
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Setup
        run: |
          gem install redis
          yarn --pure-lockfile
          yarn create-cluster
      - name: Test
        run: |
          yarn lint
          yarn test-ci